# Generated by Django 4.2.7 on 2023-11-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='DATE_TIME', null=True)),
                ('trn_ref', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRN_REF', max_length=255, null=True)),
                ('batch', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BATCH', max_length=255, null=True)),
                ('txn_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TXN_TYPE', max_length=255, null=True)),
                ('txn_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TXN_ID', max_length=255, primary_key=True, serialize=False)),
                ('issuer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ISSUER', max_length=255, null=True)),
                ('acquirer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACQUIRER', max_length=255, null=True)),
                ('issuer_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ISSUER_CODE', max_length=255, null=True)),
                ('acquirer_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACQUIRER_CODE', max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BRANCH_NAME', max_length=255, null=True)),
                ('agentnames', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENTNAMES', max_length=255, null=True)),
                ('channel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CHANNEL', max_length=255, null=True)),
                ('agent_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENT_CODE', max_length=255, null=True)),
                ('agent_code_alias', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENT_CODE_ALIAS', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=18, null=True)),
                ('acc_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACC_NO', max_length=255, null=True)),
                ('stan', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STAN', max_length=255, null=True)),
                ('fee', models.DecimalField(blank=True, db_column='FEE', decimal_places=2, max_digits=18, null=True)),
                ('request_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='REQUEST_TYPE', max_length=255, null=True)),
                ('trn_ref_0', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRAN_REF_0', max_length=255, null=True)),
                ('trn_ref_1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRAN_REF_1', max_length=255, null=True)),
                ('trn_status_0', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRAN_STATUS_0', max_length=255, null=True)),
                ('trn_status_1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRAN_STATUS_1', max_length=255, null=True)),
                ('beneficiary_entity', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BENEFICIARY_ENTITY', max_length=255, null=True)),
                ('issuer_commission', models.DecimalField(blank=True, db_column='ISSUER_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('acquirer_commission', models.DecimalField(blank=True, db_column='ACQUIRER_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('agent_commission', models.DecimalField(blank=True, db_column='AGENT_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('abc_commission', models.DecimalField(blank=True, db_column='ABC_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('response_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RESPONSE_CODE', max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRANSACTION_STATUS', max_length=255, null=True)),
                ('processing_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PROCESSING_CODE', max_length=255, null=True)),
                ('Tel_num', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TEL_NUMBER', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('swift_code', models.CharField(max_length=10, unique=True)),
                ('bank_code', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankMapping',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon.bank')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, db_column='DATE_TIME', default=django.utils.timezone.now, null=True)),
                ('recon_id', models.CharField(blank=True, db_column='RECON_ID', max_length=35, null=True)),
                ('bank_id', models.CharField(blank=True, db_column='BANK_ID', max_length=15, null=True)),
                ('rq_date_range', models.CharField(blank=True, db_column='RQ_DATE_RANGE', max_length=255, null=True)),
                ('upld_rws', models.CharField(blank=True, db_column='UPLD_RWS', max_length=15, null=True)),
                ('rq_rws', models.CharField(blank=True, db_column='RQ_RWS', max_length=15, null=True)),
                ('recon_rws', models.CharField(blank=True, db_column='RECON_RWS', max_length=15, null=True)),
                ('unrecon_rws', models.CharField(blank=True, db_column='UNRECON_RWS', max_length=15, null=True)),
                ('excep_rws', models.CharField(blank=True, db_column='EXCEP_RWS', max_length=15, null=True)),
                ('feedback', models.TextField(blank=True, db_column='FEEDBACK', null=True)),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ReconLog',
            },
        ),
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, db_column='DATE_TIME', default=django.utils.timezone.now, null=True)),
                ('tran_date', models.DateTimeField(blank=True, db_column='TRAN_DATE', null=True)),
                ('trn_ref', models.CharField(blank=True, db_column='TRN_REF', max_length=255, null=True, unique=True)),
                ('batch', models.CharField(blank=True, db_column='BATCH', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=18, null=True)),
                ('acquirer_code', models.CharField(blank=True, db_column='ACQUIRER_CODE', max_length=255, null=True)),
                ('issuer_code', models.CharField(blank=True, db_column='ISSUER_CODE', max_length=255, null=True)),
                ('excep_flag', models.CharField(blank=True, db_column='EXCEP_FLAG', max_length=6, null=True)),
                ('acq_flg', models.CharField(blank=True, db_column='ACQ_FLG', max_length=6, null=True)),
                ('iss_flg', models.CharField(blank=True, db_column='ISS_FLG', max_length=6, null=True)),
                ('acq_flg_date', models.DateTimeField(blank=True, db_column='ACQ_FLG_DATE', null=True)),
                ('iss_flg_date', models.DateTimeField(blank=True, db_column='ISS_FLG_DATE', null=True)),
                ('last_modified_by_user', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Recon',
            },
        ),
    ]
